# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x15\x63om.vktest.grpc.proto\"7\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\x05value\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_value\"5\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"Q\n\x0bGetResponse\x12\x12\n\x05value\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\tB\x08\n\x06_value\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"G\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"1\n\x0cRangeRequest\x12\x11\n\tkey_since\x18\x01 \x01(\t\x12\x0e\n\x06key_to\x18\x02 \x01(\t\"+\n\rRangeResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x0e\n\x0c\x43ountRequest\"5\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xae\x03\n\x0fKeyValueService\x12L\n\x03Put\x12!.com.vktest.grpc.proto.PutRequest\x1a\".com.vktest.grpc.proto.PutResponse\x12L\n\x03Get\x12!.com.vktest.grpc.proto.GetRequest\x1a\".com.vktest.grpc.proto.GetResponse\x12U\n\x06\x44\x65lete\x12$.com.vktest.grpc.proto.DeleteRequest\x1a%.com.vktest.grpc.proto.DeleteResponse\x12T\n\x05Range\x12#.com.vktest.grpc.proto.RangeRequest\x1a$.com.vktest.grpc.proto.RangeResponse0\x01\x12R\n\x05\x43ount\x12#.com.vktest.grpc.proto.CountRequest\x1a$.com.vktest.grpc.proto.CountResponseB&\n\x15\x63om.vktest.grpc.protoB\x0bServiceGrpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.vktest.grpc.protoB\013ServiceGrpcP\001'
  _globals['_PUTREQUEST']._serialized_start=40
  _globals['_PUTREQUEST']._serialized_end=95
  _globals['_PUTRESPONSE']._serialized_start=97
  _globals['_PUTRESPONSE']._serialized_end=150
  _globals['_GETREQUEST']._serialized_start=152
  _globals['_GETREQUEST']._serialized_end=177
  _globals['_GETRESPONSE']._serialized_start=179
  _globals['_GETRESPONSE']._serialized_end=260
  _globals['_DELETEREQUEST']._serialized_start=262
  _globals['_DELETEREQUEST']._serialized_end=290
  _globals['_DELETERESPONSE']._serialized_start=292
  _globals['_DELETERESPONSE']._serialized_end=363
  _globals['_RANGEREQUEST']._serialized_start=365
  _globals['_RANGEREQUEST']._serialized_end=414
  _globals['_RANGERESPONSE']._serialized_start=416
  _globals['_RANGERESPONSE']._serialized_end=459
  _globals['_COUNTREQUEST']._serialized_start=461
  _globals['_COUNTREQUEST']._serialized_end=475
  _globals['_COUNTRESPONSE']._serialized_start=477
  _globals['_COUNTRESPONSE']._serialized_end=530
  _globals['_KEYVALUESERVICE']._serialized_start=533
  _globals['_KEYVALUESERVICE']._serialized_end=963
# @@protoc_insertion_point(module_scope)
